SELECT FLAVOR
FROM (SELECT A.FLAVOR, SUM(A.TOTAL_ORDER)+SUM(B.TOTAL_ORDER) AS TOTAL
      FROM FIRST_HALF A
        INNER JOIN JULY B ON A.FLAVOR = B.FLAVOR
      GROUP BY A.FLAVOR
      ORDER BY TOTAL DESC)
WHERE ROWNUM <= 3      