SELECT MCDP_CD AS "진료과코드", COUNT(*) AS "5월예약건수"
FROM APPOINTMENT
WHERE TO_CHAR(APNT_YMD, 'YYYYMMDD') >= '20220501' AND TO_CHAR(APNT_YMD, 'YYYYMMDD') < '20220601'
GROUP BY MCDP_CD
ORDER BY "5월예약건수", "진료과코드"